# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upgrade system
      run: apt update && apt upgrade -y
    - name: Install docker
      run: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    - name: Install docker-compose
      run: apt install -y docker-compose
    - name: Build project
      run: docker-compose run --rm gradle
