# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install JDK 11
      run: wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add - && sudo add-apt-repository 'deb https://apt.corretto.aws stable main' &&  sudo apt-get update && sudo apt-get install -y java-11-amazon-corretto-jdk
    - name: Install Gradle 6.3
      run: wget https://downloads.gradle-dn.com/distributions/gradle-6.3-bin.zip && unzip gradle-6.3-bin.zip
    - name: Build project
      run: ./gradle-6.3/bin/gradle build --no-daemon
